version: 0.2

env:
  variables:
    NPM_CONFIG_UNSAFE_PERM: 'true'

phases:
  install:
    commands:
      - echo Install phase started on `date`...
      - npm install
      - echo Install phase completed on `date`...
  pre_build:
    commands:
      - echo Pre-Build = Build started on `date`
  build:
    commands:
      - echo Build phase started on `date`...
      - npm run build
      - echo Build phase completed on `date`...

  post_build:
    commands:
      - echo Post-Build phase started on `date`...

      - echo Installed dependencies are listed below

      - npm list --depth 0

      - npm run copy:package-files

      - echo Post-Build phase completed on `date`...

artifacts:
  files:
    - '**/*'
  base-directory: dist