#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling,linting and building your project before committing'

# lint staged files
npm run lint-staged ||
    (
        echo 'Linting failed. Make the required changes listed above, add changes and try to commit again.'

        false
    )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am commiting this now. ✅✅✅✅'
